# Generated by Django 5.0.6 on 2024-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_weight_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
